name: lua

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
         luaVersion: ["luajit"]

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: leafo/gh-actions-luarocks@v4.0.0
    - name: Install
      run: |
        apt update && \
        apt install -y build-essential libreadline-dev zip unzip cmake wget luajit libluajit-5.1-dev && \
        wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz && \
        tar zxpf luarocks-3.8.0.tar.gz && \
        cd luarocks-3.8.0 && \
        ./configure && \
        make && make install && \
        cd .. && \
        rm -rf luarocks-3.8.0 && \
        rm luarocks-3.8.0.tar.gz && \
        luarocks install busted && \
        luarocks install rapidjson 0.7.1 && \
        luarocks install luasocket && \
        luarocks install lua-resty-openssl 0.8.8-1 && \
        luarocks install date 2.1.2-1
    - name: Test
      run: busted spec